keys:
  - &admin_fdnt age14w56rvyhtfqvvtdd2rtg00xs2m6zssz5x7qfqcjyac9edwfucs2st5mmjm
  - &admin_fdl age1nnyztzln3fn9k5v5te2u4tmwvqxlseupk76w5k6lm70jxhks9pas0huhvk
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_fdnt
      - *admin_fdl
