{
  imports = [
    ./bat.nix
    ./btop.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./fish.nix
    ./foot.nix
    ./git.nix
    ./home-manager.nix
    ./hyprland
    ./mullvad-vpn.nix
    ./nh.nix
    ./nix-index.nix
    ./nixcord.nix
    ./nixvim.nix
    ./rebuild.nix
    ./ripgrep.nix
    ./rofi.nix
    ./spicetify.nix
    ./ssh.nix
    ./starship.nix
    ./waybar
    ./yazi
    ./zed-editor
    ./zen-browser.nix
    ./zoxide.nix
  ];
}
